import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import { mkdtemp, realpath, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createServer } from 'node:http';
import { DEFAULT_LIMITS } from '@moodcode/contracts';
import type { ToolContext } from '../ports.js';
import { ScopedToolRuntime } from '../tools/runtime/index.js';
import { CredentialBroker } from '../credentials/index.js';
import { McpClient, HttpMcpTransport, StdioMcpTransport, registerMcp, headerValue } from './index.js';
import { parseMessage } from './protocol.js';
const compiledFixture = fileURLToPath(new URL('./fixtures/server.js', import.meta.url));
const serverFile = existsSync(compiledFixture) ? compiledFixture : fileURLToPath(new URL('./fixtures/server.ts', import.meta.url));
const code = (expected: string) => (e: unknown) => { assert.equal((e as { code: string }).code, expected); return true; };
async function stdio(t: test.TestContext, version: '2026-07-28' | '2025-11-25' = '2026-07-28', timeout = 1000) { const root = await realpath(await mkdtemp(join(tmpdir(), 'moodcode-mcp-'))); const transport = new StdioMcpTransport({ command: process.execPath, args: [serverFile, version], cwd: root }); const client = new McpClient({ id: 'fixture', transport, protocolVersion: version, requestTimeoutMs: timeout }); t.after(async () => { await client.close(); await rm(root, { force: true, recursive: true }); }); await client.connect(new AbortController().signal); await client.listTools(new AbortController().signal); return { client, root }; }
function context(root: string): ToolContext { return { workspace: { id: 'w', root, gitRoot: root, branch: null, createdAt: new Date().toISOString() }, sessionId: 's', runId: 'r', toolCallId: 'call', turnId: 't', attemptId: 'a', signal: new AbortController().signal, limits: { ...DEFAULT_LIMITS }, artifactDir: root, recordCheckpoint() {} }; }
test('modern and legacy stdio initialize, call and resource read through real child processes', async t => { for (const version of ['2026-07-28', '2025-11-25'] as const) { const { client } = await stdio(t, version); const signal = new AbortController().signal; const result = await client.callTool('echo', { text: version }, client.revision, signal); assert.equal((result.content as { text: string }[])[0]?.text, JSON.stringify({ text: version })); assert.equal((await client.listResources(signal))[0]?.uri, 'fixture://one'); assert.equal(((await client.readResource('fixture://one', signal)).contents as { text: string }[])[0]?.text, 'fixture resource'); await assert.rejects(client.readResource('file:///etc/passwd', signal), code('MCP_RESOURCE_UNAVAILABLE')); } });
test('stdio server receives explicit env only and stderr cannot enter model tool output', async t => { const previous = process.env.MOODCODE_FIXTURE_SECRET; process.env.MOODCODE_FIXTURE_SECRET = 'fixture-parent-secret'; t.after(() => { if (previous === undefined) delete process.env.MOODCODE_FIXTURE_SECRET; else process.env.MOODCODE_FIXTURE_SECRET = previous; }); const { client } = await stdio(t); const result = await client.callTool('env_check', {}, client.revision, new AbortController().signal); assert.equal((result.content as { text: string }[])[0]?.text, 'absent'); assert.ok(!JSON.stringify(result).includes('private stderr')); });
test('stdio abort sends cancellation and connection remains usable without replaying an effect', async t => { const { client } = await stdio(t); const controller = new AbortController(); const pending = client.callTool('hang', {}, client.revision, controller.signal); setTimeout(() => controller.abort(), 10); await assert.rejects(pending, code('MCP_CANCELLED')); const result = await client.callTool('cancel_count', {}, client.revision, new AbortController().signal); assert.equal((result.content as { text: string }[])[0]?.text, '1'); });
test('stdio request timeout cancels one request while late responses cannot settle later identities', async t => { const { client } = await stdio(t, '2026-07-28', 100); await assert.rejects(client.callTool('hang', {}, client.revision, new AbortController().signal), code('MCP_REQUEST_TIMEOUT')); assert.equal(((await client.callTool('cancel_count', {}, client.revision, new AbortController().signal)).content as { text: string }[])[0]?.text, '1'); });
test('invalid and oversized stdio frames disconnect and clean up the server', async t => { for (const [toolName, expected] of [['invalid_frame', 'MCP_INVALID_MESSAGE'], ['oversize', 'MCP_MESSAGE_LIMIT']]) { const { client } = await stdio(t); await assert.rejects(client.callTool(toolName!, {}, client.revision, new AbortController().signal), code(expected!)); assert.equal(client.connected, false); } });
test('MCP remote tool annotations cannot grant read authority and disconnected catalogue is stale', async t => { const { client, root } = await stdio(t); const runtime = new ScopedToolRuntime(); const registration = await registerMcp(client, runtime, new AbortController().signal); const catalogue = runtime.catalogue(registration.scopeId); const tool = runtime.resolve(catalogue, 'mcp_fixture_echo'); assert.equal(tool.effectClass, 'unknown'); const prepared = await tool.prepare({ hi: 'value' }, context(root)); assert.equal(prepared.requiresApproval, true); await registration.close(); assert.throws(() => runtime.resolve(catalogue, 'mcp_fixture_echo'), code('TOOL_CATALOGUE_STALE')); await assert.rejects(tool.execute(prepared, context(root)), code('TOOL_CATALOGUE_STALE')); });
test('tools/list_changed unregisters old scope and requires fresh discovery and approval', async t => { const { client, root } = await stdio(t); const runtime = new ScopedToolRuntime(); const registration = await registerMcp(client, runtime, new AbortController().signal); const catalogue = runtime.catalogue(registration.scopeId); const old = runtime.resolve(catalogue, 'mcp_fixture_echo'); const prepared = await old.prepare({}, context(root)); await client.callTool('list_changed', {}, client.revision, new AbortController().signal); assert.equal(runtime.catalogue(registration.scopeId).tools.length, 0); await assert.rejects(old.execute(prepared, context(root)), code('TOOL_CATALOGUE_STALE')); });
async function httpFixture(t: test.TestContext, version: '2026-07-28' | '2025-11-25' = '2026-07-28') {
  const received: { method: string; headers: import('node:http').IncomingHttpHeaders; body: Record<string, any> }[] = [];
  const server = createServer(async (req, res) => { let body = ''; for await (const chunk of req) body += chunk; if (req.method === 'DELETE') { received.push({ method: 'DELETE', headers: req.headers, body: {} }); res.writeHead(204); res.end(); return; } const request = JSON.parse(body); received.push({ method: request.method, headers: req.headers, body: request }); if (request.id === undefined) { res.writeHead(202); res.end(); return; } let result: unknown;
    if (request.method === 'server/discover') result = { resultType: 'complete', supportedVersions: [version], capabilities: { tools: {}, resources: {} } };
    else if (request.method === 'initialize') { res.setHeader('Mcp-Session-Id', 'fixture-session'); result = { protocolVersion: version, capabilities: { tools: {}, resources: {} }, serverInfo: { name: 'http-fixture', version: '1' } }; }
    else if (request.method === 'tools/list') result = { resultType: 'complete', tools: [{ name: 'echo', description: 'HTTP fixture', inputSchema: { type: 'object', properties: { region: { type: 'string', 'x-mcp-header': 'Region' } } } }, { name: 'invalid_header', inputSchema: { type: 'object', properties: { region: { type: 'number', 'x-mcp-header': 'Region' } } } }] };
    else if (request.method === 'resources/list') result = { resultType: 'complete', resources: [{ uri: 'fixture://remote', name: 'remote' }] };
    else if (request.method === 'resources/read') result = { resultType: 'complete', contents: [{ uri: request.params.uri, text: 'remote-resource' }] };
    else if (request.method === 'tools/call') { if (request.params.arguments.hang) { req.on('close', () => res.destroy()); return; } if (request.params.arguments.inputRequired) result = { resultType: 'input_required', inputRequests: { ask: {} } }; else result = { resultType: 'complete', content: [{ type: 'text', text: 'http-result' }], structuredContent: { header: req.headers['mcp-param-region'] ?? null } }; }
    const message = JSON.stringify({ jsonrpc: '2.0', id: request.id, result });
    if (request.method === 'tools/call' && request.params.arguments.sse) { res.writeHead(200, { 'Content-Type': 'text/event-stream' }); res.write(': comment\r\n\r\n'); res.write('data: ' + message.slice(0, 10)); setTimeout(() => res.end(message.slice(10) + '\r\n\r\n'), 5); } else { res.writeHead(200, { 'Content-Type': 'application/json' }); res.end(message); }
  }); await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve)); t.after(async () => { server.closeAllConnections(); await new Promise<void>(resolve => server.close(() => resolve())); }); const address = server.address() as { port: number }; return { url: `http://127.0.0.1:${address.port}/mcp`, received };
}
test('modern HTTP JSON/SSE mirror metadata and valid annotated params; invalid tool header is excluded', async t => { const { url, received } = await httpFixture(t); const client = new McpClient({ id: 'http', transport: new HttpMcpTransport({ url }) }); t.after(() => client.close()); const signal = new AbortController().signal; await client.connect(signal); const tools = await client.listTools(signal); assert.deepEqual(tools.map(tool => tool.name), ['echo']); const result = await client.callTool('echo', { region: '서울', sse: true }, client.revision, signal); assert.equal((result.content as { text: string }[])[0]?.text, 'http-result'); const request = received.find(r => r.method === 'tools/call')!; assert.equal(request.headers['mcp-method'], 'tools/call'); assert.equal(request.headers['mcp-name'], 'echo'); assert.equal(request.headers['mcp-param-region'], headerValue('서울')); assert.equal(request.headers['mcp-protocol-version'], request.body.params._meta['io.modelcontextprotocol/protocolVersion']); });
test('legacy HTTP session header, initialized notification and DELETE cleanup work', async t => { const { url, received } = await httpFixture(t, '2025-11-25'); const client = new McpClient({ id: 'legacy', protocolVersion: '2025-11-25', transport: new HttpMcpTransport({ url, protocolVersion: '2025-11-25' }) }); const signal = new AbortController().signal; await client.connect(signal); await client.listTools(signal); await client.callTool('echo', {}, client.revision, signal); await client.close(); assert.equal(received.find(r => r.method === 'tools/call')?.headers['mcp-session-id'], 'fixture-session'); assert.ok(received.some(r => r.method === 'notifications/initialized')); assert.ok(received.some(r => r.method === 'DELETE')); });
test('HTTP broker applies fixture host credential only to exact audience, never to tool data', async t => { const { url, received } = await httpFixture(t); const broker = new CredentialBroker({ async resolve() { return { bearerToken: 'fixture-token', expiresAt: Date.now() + 60_000 }; } }); const client = new McpClient({ id: 'auth', transport: new HttpMcpTransport({ url, credential: { broker, reference: { id: 'host:fixture', audience: url } } }) }); t.after(() => client.close()); const signal = new AbortController().signal; await client.connect(signal); await client.listTools(signal); const result = await client.callTool('echo', {}, client.revision, signal); assert.equal(received.find(r => r.method === 'tools/call')?.headers.authorization, 'Bearer fixture-token'); assert.ok(!JSON.stringify(result).includes('fixture-token')); assert.ok(!JSON.stringify(broker).includes('fixture-token')); });
test('HTTP stream abort is bounded and required host interactions are explicit unsupported', async t => { const { url } = await httpFixture(t); const client = new McpClient({ id: 'cancel', transport: new HttpMcpTransport({ url }), requestTimeoutMs: 1000 }); t.after(() => client.close()); const signal = new AbortController().signal; await client.connect(signal); await client.listTools(signal); const controller = new AbortController(); const pending = client.callTool('echo', { hang: true }, client.revision, controller.signal); setTimeout(() => controller.abort(), 10); await assert.rejects(pending, code('MCP_CANCELLED')); await assert.rejects(client.callTool('echo', { inputRequired: true }, client.revision, signal), code('MCP_INPUT_REQUIRED_UNSUPPORTED')); });
test('HTTP redirects, credentials in URL and wrong response IDs are rejected', async t => { assert.throws(() => new HttpMcpTransport({ url: 'https://user:password@example.com/mcp' }), code('INVALID_MCP_HTTP')); const server = createServer((_req, res) => { res.writeHead(302, { Location: 'http://127.0.0.1:1/' }); res.end(); }); await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve)); t.after(async () => { server.closeAllConnections(); await new Promise<void>(resolve => server.close(() => resolve())); }); const address = server.address() as { port: number }; const client = new McpClient({ id: 'redirect', transport: new HttpMcpTransport({ url: `http://127.0.0.1:${address.port}/mcp` }) }); await assert.rejects(client.connect(new AbortController().signal), code('MCP_HTTP_FAILED')); assert.equal(client.connected, false); });
test('JSON-RPC batch, missing IDs, multiple result/error and invalid UTF8 are rejected', () => { for (const data of [[], { jsonrpc: '2.0', result: {} }, { jsonrpc: '2.0', id: 1, result: {}, error: { code: -1, message: 'x' } }]) assert.throws(() => parseMessage(JSON.stringify(data)), code('MCP_INVALID_MESSAGE')); assert.throws(() => parseMessage(Buffer.from([0xff])), code('MCP_INVALID_MESSAGE')); });
test('stdio close terminates its owned POSIX descendant process group', { skip: process.platform === 'win32' }, async t => { const { client } = await stdio(t); const result = await client.callTool('start_descendant', {}, client.revision, new AbortController().signal); const pid = Number((result.content as { text: string }[])[0]!.text); assert.ok(pid > 0); await client.close(); let alive = true; for (let attempt = 0; attempt < 25; attempt++) { try { process.kill(pid, 0); } catch { alive = false; break; } await new Promise(resolve => setTimeout(resolve, 20)); } assert.equal(alive, false); });
test('stdio spawn failure reports MCP_START_FAILED with a confirmed never-started outcome', async t => { const root = await realpath(await mkdtemp(join(tmpdir(), 'moodcode-mcp-'))); t.after(() => rm(root, { force: true, recursive: true })); const notExecutable = join(root, 'not-executable'); await writeFile(notExecutable, '#!/bin/sh\n', { mode: 0o644 }); for (const command of [join(root, 'missing'), ...(process.platform === 'win32' ? [] : [notExecutable])]) { const events: unknown[] = []; const transport = new StdioMcpTransport({ command, cwd: root, observer: { beforeStart: () => events.push('beforeStart'), started: pid => events.push({ started: pid }), closed: outcome => events.push(outcome) } }); const client = new McpClient({ id: 'unstarted', transport }); await assert.rejects(client.connect(new AbortController().signal), code('MCP_START_FAILED')); await client.close(); assert.deepEqual(events, ['beforeStart', { exitCode: null, cleanupConfirmed: true, started: false }]); } });
test('HTTP wrong response id and total-byte limit close the captured transport', async () => { for (const [response, expected] of [[JSON.stringify({ jsonrpc: '2.0', id: 999, result: {} }), 'MCP_RESPONSE_ID_MISMATCH'], [JSON.stringify({ jsonrpc: '2.0', id: 1, result: { text: 'x'.repeat(1_048_576) } }), 'MCP_MESSAGE_LIMIT']]) { let closed = false; const transport = new HttpMcpTransport({ url: 'http://127.0.0.1:1/mcp', fetch: (async () => new Response(response, { headers: { 'Content-Type': 'application/json' } })) as typeof fetch }); await transport.start(() => assert.fail('invalid response must not be delivered'), () => { closed = true; }); await assert.rejects(transport.send({ jsonrpc: '2.0', id: 1, method: 'server/discover', params: { _meta: { 'io.modelcontextprotocol/protocolVersion': '2026-07-28' } } }), code(expected!)); assert.equal(closed, true); } });
test('HTTP SSE parses byte-dripped frames and keeps MCP failure codes', async () => {
  const encoder = new TextEncoder();
  const send = async (chunks: readonly Uint8Array[]) => {
    const received: unknown[] = []; let closed = false;
    const transport = new HttpMcpTransport({ url: 'http://127.0.0.1:1/mcp', fetch: (async () => new Response(new ReadableStream<Uint8Array>({ start(controller) { for (const chunk of chunks) controller.enqueue(chunk); controller.close(); } }), { headers: { 'Content-Type': 'text/event-stream' } })) as typeof fetch });
    await transport.start(message => received.push(message), () => { closed = true; });
    const sent = transport.send({ jsonrpc: '2.0', id: 1, method: 'server/discover', params: { _meta: { 'io.modelcontextprotocol/protocolVersion': '2026-07-28' } } });
    return { sent, received, closed: () => closed };
  };
  const stream = encoder.encode('\uFEFF: comment\r\n\r\nevent: message\r\nid: 7\r\ndata:\r\n\r\ndata: {"jsonrpc":"2.0","method":"notifications/message",\r\ndata:"params":{"text":"한글"}}\r\n\r\ndata: {"jsonrpc":"2.0","id":1,"result":{}}\n\n');
  const dripped = await send([...stream].map(byte => Uint8Array.of(byte))); await dripped.sent;
  assert.deepEqual(dripped.received, [{ jsonrpc: '2.0', method: 'notifications/message', params: { text: '한글' } }, { jsonrpc: '2.0', id: 1, result: {} }]);
  for (const [chunks, expected, closes] of [
    [[encoder.encode('data: {"jsonrpc":"2.0","id":1,"result":{}}\n')], 'MCP_DISCONNECTED', true],
    [[Uint8Array.of(...encoder.encode('data: '), 0xff, 10, 10)], 'MCP_HTTP_FAILED', false],
    [[encoder.encode('data: '), ...Array.from({ length: 17 }, () => new Uint8Array(65_536).fill(120))], 'MCP_MESSAGE_LIMIT', true],
  ] as const) { const result = await send(chunks); await assert.rejects(result.sent, code(expected)); assert.equal(result.closed(), closes); assert.deepEqual(result.received, []); }
});
