import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, realpath, rm, writeFile, readFile, mkdir, symlink, chmod, access } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { DEFAULT_LIMITS, type Checkpoint } from '@moodcode/contracts';
import type { ToolContext } from '../../ports.js';
import { createExactEditTool } from './index.js';
import { createFileActionTools } from '../file-actions/index.js';
import { textHash } from '../file-actions/text.js';
const hasCode = (code: string) => (e: unknown) => { assert.equal((e as { code: string }).code, code); return true; };
async function fixture(t: test.TestContext) { const root = await realpath(await mkdtemp(join(tmpdir(), 'moodcode-edit-'))); t.after(() => rm(root, { force: true, recursive: true })); const checkpoints: Checkpoint[] = []; const context: ToolContext = { workspace: { id: 'workspace', root, gitRoot: root, branch: null, createdAt: new Date().toISOString() }, sessionId: 's', runId: 'r', toolCallId: 'call', turnId: 'turn', attemptId: 'attempt', signal: new AbortController().signal, limits: { ...DEFAULT_LIMITS }, artifactDir: root, recordCheckpoint: cp => checkpoints.push(cp) }; return { root, checkpoints, context }; }
test('exact edit preserves BOM and untouched CRLF with checkpoint and structured result', async t => {
  const { root, context, checkpoints } = await fixture(t); const original = '\ufeffone\r\ntwo\r\n'; await writeFile(join(root, 'a.txt'), original); const tool = createExactEditTool(); const prepared = await tool.prepare({ path: 'a.txt', expectedHash: textHash(original), oldString: 'two', newString: 'three' }, context);
  assert.equal(prepared.requiresApproval, true); assert.equal(prepared.preview.bom, true); assert.equal(prepared.preview.lineEndings, 'CRLF'); const result = await tool.execute(prepared, context);
  assert.equal(await readFile(join(root, 'a.txt'), 'utf8'), '\ufeffone\r\nthree\r\n'); assert.equal(checkpoints.length, 1); assert.equal(checkpoints[0]?.files[0]?.before, original); assert.equal(result.structuredResult?.outcome, 'completed'); await assert.rejects(tool.execute(prepared, context), hasCode('INVALID_PREPARED_FILE_ACTION'));
});
test('missing, repeated and overlapping old strings are rejected before effects', async t => { const { root, context, checkpoints } = await fixture(t); const content = 'aaa'; await writeFile(join(root, 'a'), content); const tool = createExactEditTool(); for (const [oldString, code] of [['z', 'EDIT_MATCH_NOT_FOUND'], ['a', 'EDIT_MATCH_AMBIGUOUS'], ['aa', 'EDIT_MATCH_AMBIGUOUS']]) await assert.rejects(tool.prepare({ path: 'a', expectedHash: textHash(content), oldString, newString: 'x' }, context), hasCode(code!)); assert.equal(await readFile(join(root, 'a'), 'utf8'), content); assert.equal(checkpoints.length, 0); });
test('changed preimage after prepare is preserved and reapproval required', async t => { const { root, context } = await fixture(t); await writeFile(join(root, 'a'), 'before'); const tool = createExactEditTool(); const prepared = await tool.prepare({ path: 'a', expectedHash: textHash('before'), oldString: 'before', newString: 'after' }, context); await writeFile(join(root, 'a'), 'external'); await assert.rejects(tool.execute(prepared, context), hasCode('PATCH_PREIMAGE_MISMATCH')); assert.equal(await readFile(join(root, 'a'), 'utf8'), 'external'); });
test('input tampering and different attempt never authorize existing prepared edit', async t => { const { root, context } = await fixture(t); await writeFile(join(root, 'a'), 'before'); const tool = createExactEditTool(); const input = { path: 'a', expectedHash: textHash('before'), oldString: 'before', newString: 'after' }; const first = await tool.prepare(input, context); first.preview.bom = true; await assert.rejects(tool.execute(first, context), hasCode('FILE_ACTION_APPROVAL_STALE')); const second = await tool.prepare(input, context); await assert.rejects(tool.execute(second, { ...context, attemptId: 'other' }), hasCode('FILE_ACTION_APPROVAL_STALE')); assert.equal(await readFile(join(root, 'a'), 'utf8'), 'before'); });
test('zero output budget still applies and records checkpoint without projection failure', async t => { const { root, context, checkpoints } = await fixture(t); context.limits.maxOutputBytes = 0; await writeFile(join(root, 'a'), 'before'); const tool = createExactEditTool(); const result = await tool.execute(await tool.prepare({ path: 'a', expectedHash: textHash('before'), oldString: 'before', newString: 'after' }, context), context); assert.equal(result.content, ''); assert.equal(result.structuredResult?.modelContent, ''); assert.equal(checkpoints[0]?.files[0]?.after, 'after'); });
test('rename and delete reuse full-content checkpoint and refuse overwrite', async t => { const { root, context, checkpoints } = await fixture(t); await writeFile(join(root, 'a'), 'move'); const [renameTool, deleteTool] = createFileActionTools(); const moved = await renameTool!.execute(await renameTool!.prepare({ path: 'a', destination: 'b', expectedHash: textHash('move') }, context), context); assert.equal(moved.isError, undefined); await assert.rejects(access(join(root, 'a'))); assert.equal(await readFile(join(root, 'b'), 'utf8'), 'move'); assert.equal(checkpoints[0]?.files.length, 2); await writeFile(join(root, 'occupied'), 'keep'); await assert.rejects(renameTool!.prepare({ path: 'b', destination: 'occupied', expectedHash: textHash('move') }, context), hasCode('PATCH_PREIMAGE_MISMATCH')); await deleteTool!.execute(await deleteTool!.prepare({ path: 'b', expectedHash: textHash('move') }, context), context); await assert.rejects(access(join(root, 'b'))); assert.equal(checkpoints[1]?.files[0]?.after, null); });
test('Git paths, binaries, directories, symlinks and custom rename mode are explicit unsupported boundaries', async t => { const { root, context } = await fixture(t); const [renameTool, deleteTool] = createFileActionTools(); await writeFile(join(root, 'binary'), Buffer.from([0, 255])); await mkdir(join(root, 'dir')); await writeFile(join(root, 'a'), 'text'); await symlink(join(root, 'a'), join(root, 'link')); for (const path of ['binary', 'dir', 'link']) await assert.rejects(deleteTool!.prepare({ path, expectedHash: textHash('text') }, context), hasCode('UNSUPPORTED_FILE_ACTION')); for (const path of ['.git/config', '.git./config', 'GIT~1/config', 'node_modules /x', '.g\u200cit/config']) await assert.rejects(deleteTool!.prepare({ path, expectedHash: textHash('text') }, context), hasCode('INVALID_FILE_ACTION_PATH')); await chmod(join(root, 'a'), 0o755); await assert.rejects(renameTool!.prepare({ path: 'a', destination: 'b', expectedHash: textHash('text') }, context), hasCode('UNSUPPORTED_FILE_ACTION_MODE')); });
test('file actions reject parents that physically resolve into dependencies before reading them', async t => { const { root, context } = await fixture(t); await mkdir(join(root, 'node_modules', 'pkg'), { recursive: true }); await writeFile(join(root, 'node_modules', 'pkg', 'index.js'), 'old'); const alias = 'node_module\u017f'; if (!await access(join(root, alias)).then(() => true, () => false)) { t.skip('volume does not fold this name onto node_modules'); return; } const [renameTool, deleteTool] = createFileActionTools(); const path = `${alias}/pkg/index.js`, expectedHash = textHash('old'); await assert.rejects(deleteTool!.prepare({ path, expectedHash }, context), hasCode('UNSAFE_FILE_ACTION_PATH')); await assert.rejects(renameTool!.prepare({ path, destination: 'moved.js', expectedHash }, context), hasCode('UNSAFE_FILE_ACTION_PATH')); await assert.rejects(createExactEditTool().prepare({ path, expectedHash, oldString: 'old', newString: 'new' }, context), hasCode('UNSAFE_FILE_ACTION_PATH')); assert.equal(await readFile(join(root, 'node_modules', 'pkg', 'index.js'), 'utf8'), 'old'); await assert.rejects(access(join(root, 'moved.js'))); });
